version: '3.6'

volumes:
  mysql_data_volume:

services:
  api:
    container_name: api 
    image: car-list-api:latest
    restart: 'on-failure'
    build:
      dockerfile: ./docker/Dockerfile
      context: ./api/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./env/api.env
    environment:
      - NODE_ENV=develop
    volumes:
      - ./api/:/opt/app/
    ports:
      - 3000:3000
      - 59229:9229
    command: ["npm", "run", "start:dev"]
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "3000"]
      interval: 10s
      start_period: 30s
      retries: 3
      timeout: 5s
    networks:
      - car-list

  db:
    container_name: db
    image: mysql:8.0.36-debian
    restart: 'on-failure'
    env_file:
      - env/db.env
    command:
      - --ssl=0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 30s
    volumes:
      - mysql_data_volume:/var/lib/mysql
    ports: 
      - 33306:3306
    networks:
      - car-list
    
networks:
  car-list:
    driver: bridge
    name: car-list
    ipam:
      config:
        - subnet: 172.20.30.0/24